package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.BuildStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.VisualStudioStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.visualStudio
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        step {
            type = "jb.nuget.installer"
            param("nuget.path", "%teamcity.tool.NuGet.CommandLine.DEFAULT%")
            param("nuget.sources", """
                "https://www.nuget.org/api/v2/"
                "C:\NuGetPackages"
                %teamcity.nuget.feed.auth.server%
            """.trimIndent())
            param("nuget.updatePackages.mode", "sln")
            param("nugetCustomPath", "%teamcity.tool.NuGet.CommandLine.DEFAULT%")
            param("nugetPathSelector", "%teamcity.tool.NuGet.CommandLine.DEFAULT%")
            param("sln.path", "source/Log4Net.ThrottlingSmtpAppender.sln")
        }
        visualStudio {
            path = "source/Log4Net.ThrottlingSmtpAppender.sln"
            version = VisualStudioStep.VisualStudioVersion.vs2013
            runPlatform = VisualStudioStep.Platform.x86
            msBuildVersion = VisualStudioStep.MSBuildVersion.V12_0
            msBuildToolsVersion = VisualStudioStep.MSBuildToolsVersion.V12_0
            configuration = "Release"
            param("octopus_octopack_package_version", "0.%sharedBuildNumber.id4%")
        }
        step {
            name = "Package"
            type = "jb.nuget.pack"
            param("nuget.pack.as.artifact", "true")
            param("nuget.pack.include.sources", "true")
            param("nuget.pack.output.clean", "true")
            param("nuget.pack.output.directory", "Build/ackages")
            param("nuget.pack.specFile", "source/Log4Net.ThrottlingSmtpAppender.csproj")
            param("nuget.pack.version", "0.0.1.%teamcity.build.id%")
            param("nuget.path", "%teamcity.tool.NuGet.CommandLine.DEFAULT%")
            param("nugetCustomPath", "%teamcity.tool.NuGet.CommandLine.DEFAULT%")
            param("nugetPathSelector", "%teamcity.tool.NuGet.CommandLine.DEFAULT%")
        }
    }
    steps {
        update<BuildStep>(0) {
            param("nuget.sources", """
                "https://www.nuget.org/api/v2/"
                "C:\NuGetPackages"
                %teamcity.nuget.feed.httpAuth._Root.default.v2%
            """.trimIndent())
        }
    }
}
